name: Automated YouTube Live Stream

on:
  schedule:
    - cron: '03 15 * * *' # Runs every day at 8:33 PM IST
  workflow_dispatch:

jobs:
  stream-video:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Video from Google Drive
        run: |
          pipx run gdown 1dcJyK6LsVLJymqRa2RH2TxaCS299BfFz -O video.mp4

      - name: Stream to YouTube
        env:
          KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          ffmpeg -re -stream_loop 1 -i video.mp4 -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 60 -c:a aac -ar 44100 -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/$KEY"
