name: Automated YouTube Live Stream

on:
  schedule:
    # 15:30 UTC is exactly 9:00 PM IST
    - cron: '30 15 * * *'
  workflow_dispatch: # This allows you to test it manually with a button

jobs:
  stream-video:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg pipx
          pipx install gdown

      - name: Download Video from Google Drive
        # Downloading your specific file
        run: /home/runner/.local/bin/gdown --id "1wntPFRjpTjtRau3Sr1Ts_nSr3Qy8Lf7u" -O video.mp4

      - name: Stream to YouTube
        env:
          STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        # Streaming directly without re-encoding to save CPU
        run: |
          ffmpeg -re -i video.mp4 \
          -c copy \
          -f flv rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY
